-- CREACIÓN DE TABLAS.

CREATE TABLE USUARIO (IDUSER BIGINT NOT NULL, DTYPE VARCHAR(31), APELLIDO1 VARCHAR(255) NOT NULL, APELLIDO2 VARCHAR(255), FECHANACIMIENTO DATE NOT NULL, NIF VARCHAR(255) NOT NULL, NOMBRE VARCHAR(255) NOT NULL, PASSWORD VARCHAR(255) NOT NULL, TELEFONO VARCHAR(255), USER_NAME VARCHAR(255) NOT NULL, EMAIL VARCHAR(255) NOT NULL, PRIMARY KEY (IDUSER))
CREATE TABLE BECA (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), FECHAEMISION DATE NOT NULL, FECHAFIN DATE NOT NULL, NOMBRE VARCHAR(255) NOT NULL, CUANTIA INTEGER NOT NULL, PRIMARY KEY (ID))
CREATE TABLE CCJ (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255) NOT NULL, DIRECCION VARCHAR(255) NOT NULL, NACION VARCHAR(255) NOT NULL, NOMBRE VARCHAR(255) NOT NULL, REGION VARCHAR(255) NOT NULL, TELEFONO VARCHAR(255) NOT NULL, EMAIL VARCHAR(255) NOT NULL, PRIMARY KEY (ID))
CREATE TABLE JOVEN_NIÑO (ID BIGINT NOT NULL, APELLIDO1 VARCHAR(255) NOT NULL, APELLIDO2 VARCHAR(255), DESCRIPCION VARCHAR(255), APADRINADO SMALLINT DEFAULT 0 NOT NULL, FECHANACIMIENTO DATE, NACIONALIDAD VARCHAR(255) NOT NULL, NOMBRE VARCHAR(255) NOT NULL, CCJ_ID BIGINT, CP_ID BIGINT, PRIMARY KEY (ID))
CREATE TABLE CASA_POPULORUM (ID BIGINT NOT NULL, NOMBRE VARCHAR(255) NOT NULL, REGION VARCHAR(255) NOT NULL, TAM_MAX INTEGER NOT NULL, PRIMARY KEY (ID))
CREATE TABLE HISTORIAL_APADRINAMIENTO (ID BIGINT NOT NULL, APADRINADO SMALLINT DEFAULT 0 NOT NULL, FECHA_FIN DATE NOT NULL, FECHA_INICIO DATE NOT NULL, NIÑO_APADRINADO_ID BIGINT, SOCIO_APADRINA_IDUSER BIGINT, PRIMARY KEY (ID))
CREATE TABLE SOCIO (IDUSER BIGINT NOT NULL, NUM_CUENTA_BANCARIA VARCHAR(255) NOT NULL, PRIMARY KEY (IDUSER))
CREATE TABLE ADMINISTRADOR (IDUSER BIGINT NOT NULL, FECHA_ENTRADA DATE NOT NULL, IMPORTEBRUTO FLOAT NOT NULL, NUM_SS VARCHAR(255) NOT NULL, SECCION_OPERATIVA VARCHAR(255) NOT NULL, SUELDO FLOAT NOT NULL, PRIMARY KEY (IDUSER))
CREATE TABLE ENVIOS (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), ESTADO VARCHAR(255) NOT NULL, NIÑO_ENVIO_ID BIGINT, SOCIO_ENVIO_IDUSER BIGINT, PRIMARY KEY (ID))

-- CREACIÓN DE becas_obt.

CREATE TABLE becas_obt (BECA_id BIGINT NOT NULL, JOVEN_NIÑO_id BIGINT NOT NULL, PRIMARY KEY (BECA_id, JOVEN_NIÑO_id))

-- RESTRICCIONES CLAVE FORÁNEA.

ALTER TABLE JOVEN_NIÑO ADD CONSTRAINT JOVEN_NIÑO_CP_ID FOREIGN KEY (CP_ID) REFERENCES CASA_POPULORUM (ID)
ALTER TABLE JOVEN_NIÑO ADD CONSTRAINT JOVEN_NIÑO_CCJ_ID FOREIGN KEY (CCJ_ID) REFERENCES CCJ (ID)
ALTER TABLE HISTORIAL_APADRINAMIENTO ADD CONSTRAINT HSTRLPDRNMNÑPDRNDD FOREIGN KEY (NIÑO_APADRINADO_ID) REFERENCES JOVEN_NIÑO (ID)
ALTER TABLE HISTORIAL_APADRINAMIENTO ADD CONSTRAINT HSTRLPDRNSCPDRNDSR FOREIGN KEY (SOCIO_APADRINA_IDUSER) REFERENCES USUARIO (IDUSER)
ALTER TABLE SOCIO ADD CONSTRAINT FK_SOCIO_IDUSER FOREIGN KEY (IDUSER) REFERENCES USUARIO (IDUSER)
ALTER TABLE ADMINISTRADOR ADD CONSTRAINT DMINISTRADORIDUSER FOREIGN KEY (IDUSER) REFERENCES USUARIO (IDUSER)
ALTER TABLE ENVIOS ADD CONSTRAINT NVOSSCOENVIOIDUSER FOREIGN KEY (SOCIO_ENVIO_IDUSER) REFERENCES USUARIO (IDUSER)
ALTER TABLE ENVIOS ADD CONSTRAINT ENVIOSNIÑOENVIO_ID FOREIGN KEY (NIÑO_ENVIO_ID) REFERENCES JOVEN_NIÑO (ID)
ALTER TABLE becas_obt ADD CONSTRAINT bcasobtJOVENNIÑOid FOREIGN KEY (JOVEN_NIÑO_id) REFERENCES JOVEN_NIÑO (ID)
ALTER TABLE becas_obt ADD CONSTRAINT becas_obt_BECA_id FOREIGN KEY (BECA_id) REFERENCES BECA (ID)

CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
